steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'endpoint-slide4vr-pdf2png', '--image', 'gcr.io/$PROJECT_ID/kuda-proxy', '--region', 'us-central1', '--platform', 'managed', '--set-env-vars', 'TARGET_URL=https://pdf2png-dnb6froqha-uc.a.run.app,USE_GOOGLE_JWT=true']
